# Generated by Django 5.0.4 on 2024-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_request_loan_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='soft_copy',
            field=models.FileField(blank=True, null=True, upload_to='book_soft_copies'),
        ),
    ]
