# Generated by Django 5.0.4 on 2024-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_cover_image_book_soft_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
